spring:
  application:
    name: onlinebookstore

  datasource:
    url:
      jdbc:mysql://localhost:3306/onlinebookstore?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


server:
  port: 6000